os: Visual Studio 2015
version: 0.0.1.{build}

clone_folder: c:\foo_music_tagger

configuration:
- Debug
- Release

environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib32-msvc-14.0
  VS_VERSION: 14 2015
  VS_PLATFORM: win32

install:
- ps: c:\foo_music_tagger\Scripts\installDependency.ps1

before_build:
- cmake -H. -BBuild/VS -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VSPLATFORM% -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=true -Wno-dev -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"

cache:
  - ThirdParty\Catch -> appveyor.yml

build:
  project: Build\VS\INSTALL.vcxproj
  parallel: true
  verbosity: minimal

test_script:
- cd Build\VS
- ctest --verbose --build-config %CONFIGURATION%